--INSERT
CREATE OR REPLACE PROCEDURE PRC_INS_MEGAG_DESP_ARQUIVO(
    p_CODDESPESA     IN  CONSINCO.MEGAG_DESP_ARQUIVO.CODDESPESA%TYPE,
    p_NOMEARQUIVO    IN  CONSINCO.MEGAG_DESP_ARQUIVO.NOMEARQUIVO%TYPE,
    p_TIPOARQUIVO    IN  CONSINCO.MEGAG_DESP_ARQUIVO.TIPOARQUIVO%TYPE DEFAULT NULL,
    p_CODARQUIVO_OUT OUT CONSINCO.MEGAG_DESP_ARQUIVO.CODARQUIVO%TYPE,
    s_sfx            OUT VARCHAR2,
    s_ico            OUT VARCHAR2,
    s_tiporet        OUT VARCHAR2,
    s_msg            OUT VARCHAR2
) IS
BEGIN
    INSERT INTO CONSINCO.MEGAG_DESP_ARQUIVO(CODDESPESA, NOMEARQUIVO, TIPOARQUIVO)
    VALUES(p_CODDESPESA, p_NOMEARQUIVO, p_TIPOARQUIVO)
    RETURNING CODARQUIVO INTO p_CODARQUIVO_OUT;

    s_sfx := 'success'; s_ico := 'success'; s_tiporet := 'S'; s_msg := 'Arquivo inserido.';
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        s_sfx := 'error'; s_ico := 'danger'; s_tiporet := 'E'; s_msg := 'Erro: ' || SQLERRM;
END PRC_INS_MEGAG_DESP_ARQUIVO;
/

--SELECT
CREATE OR REPLACE PROCEDURE PRC_SEL_MEGAG_DESP_ARQUIVO(
    p_CODARQUIVO IN  CONSINCO.MEGAG_DESP_ARQUIVO.CODARQUIVO%TYPE DEFAULT NULL,
    p_CODDESPESA IN  CONSINCO.MEGAG_DESP_ARQUIVO.CODDESPESA%TYPE DEFAULT NULL,
    p_RESULT     OUT SYS_REFCURSOR,
    s_sfx        OUT VARCHAR2,
    s_ico        OUT VARCHAR2,
    s_tiporet    OUT VARCHAR2,
    s_msg        OUT VARCHAR2
) IS
BEGIN
    OPEN p_RESULT FOR
        SELECT * FROM CONSINCO.MEGAG_DESP_ARQUIVO
        WHERE (p_CODARQUIVO IS NULL OR CODARQUIVO = p_CODARQUIVO)
          AND (p_CODDESPESA IS NULL OR CODDESPESA = p_CODDESPESA);
    s_sfx := 'success'; s_ico := 'success'; s_tiporet := 'S'; s_msg := 'OK';
END PRC_SEL_MEGAG_DESP_ARQUIVO;
/
