--INSERT
CREATE OR REPLACE PROCEDURE PRC_INS_MEGAG_DESP_ARQUIVO(
    p_CODDESPESA       IN MEGAG_DESP_ARQUIVO.CODDESPESA%TYPE,
    p_NOMEARQUIVO      IN MEGAG_DESP_ARQUIVO.NOMEARQUIVO%TYPE,
    p_TIPOARQUIVO      IN MEGAG_DESP_ARQUIVO.TIPOARQUIVO%TYPE DEFAULT NULL,
    p_CODARQUIVO_OUT   OUT MEGAG_DESP_ARQUIVO.CODARQUIVO%TYPE
)
IS
BEGIN
/*
* REGRA DE NEGÓCIO
* loop para o usuário inserir quantos arquivos desejar vinculados a despesa.Será feito no back-end
*/
    INSERT INTO MEGAG_DESP_ARQUIVO(
        CODDESPESA,
        NOMEARQUIVO,
        TIPOARQUIVO
    )
    VALUES(
        p_CODDESPESA,
        p_NOMEARQUIVO,
        p_TIPOARQUIVO
    )
    RETURNING CODARQUIVO INTO p_CODARQUIVO_OUT;

END PRC_INS_MEGAG_DESP_ARQUIVO;
/

--SELECT
CREATE OR REPLACE PROCEDURE PRC_SEL_MEGAG_DESP_ARQUIVO(
    p_CODARQUIVO   IN MEGAG_DESP_ARQUIVO.CODARQUIVO%TYPE DEFAULT NULL,
    p_CODDESPESA   IN MEGAG_DESP_ARQUIVO.CODDESPESA%TYPE DEFAULT NULL,
    p_RESULT       OUT SYS_REFCURSOR
)
IS
BEGIN
/*
* REGRA DE NEGÓCIO
*/
    OPEN p_RESULT FOR
        SELECT CODARQUIVO,
               CODDESPESA,
               NOMEARQUIVO,
               TIPOARQUIVO,
               DTAINCLUSAO,
               DTAALTERACAO
          FROM MEGAG_DESP_ARQUIVO
         WHERE (p_CODARQUIVO IS NULL OR CODARQUIVO = p_CODARQUIVO)
           AND (p_CODDESPESA IS NULL OR CODDESPESA = p_CODDESPESA);

END PRC_SEL_MEGAG_DESP_ARQUIVO;
/

--UPDATE
CREATE OR REPLACE PROCEDURE PRC_UPD_MEGAG_DESP_ARQUIVO(
    p_CODARQUIVO   IN MEGAG_DESP_ARQUIVO.CODARQUIVO%TYPE,
    p_NOMEARQUIVO  IN MEGAG_DESP_ARQUIVO.NOMEARQUIVO%TYPE,
    p_TIPOARQUIVO  IN MEGAG_DESP_ARQUIVO.TIPOARQUIVO%TYPE DEFAULT NULL
)
IS
BEGIN
/*
* REGRA DE NEGÓCIO
*/
    UPDATE MEGAG_DESP_ARQUIVO
       SET NOMEARQUIVO  = p_NOMEARQUIVO,
           TIPOARQUIVO  = p_TIPOARQUIVO,
           DTAALTERACAO = SYSDATE
     WHERE CODARQUIVO = p_CODARQUIVO;

END PRC_UPD_MEGAG_DESP_ARQUIVO;
/


--DELETE
CREATE OR REPLACE PROCEDURE PRC_DEL_MEGAG_DESP_ARQUIVO(
    p_CODARQUIVO IN MEGAG_DESP_ARQUIVO.CODARQUIVO%TYPE
)
IS
BEGIN
/*
* REGRA DE NEGÓCIO
*/
    DELETE FROM MEGAG_DESP_ARQUIVO
     WHERE CODARQUIVO = p_CODARQUIVO;

END PRC_DEL_MEGAG_DESP_ARQUIVO;
/
