-- Estrutura necessaria para ativacao de push web via Firebase.
-- Execute no schema configurado como DB_SCHEMA na aplicacao.

CREATE TABLE MEGAG_PUSH_TOKENS (
    ID                NUMBER NOT NULL,
    USUARIO           VARCHAR2(100) NOT NULL,
    TOKEN             VARCHAR2(4000) NOT NULL,
    DEVICE_PLATFORM   VARCHAR2(30) DEFAULT 'web' NOT NULL,
    USER_AGENT        VARCHAR2(1000),
    ENDPOINT_ORIGEM   VARCHAR2(500),
    ATIVO             CHAR(1) DEFAULT 'S' NOT NULL,
    CRIADO_EM         DATE DEFAULT SYSDATE,
    ULTIMO_ACESSO_EM  DATE,

    CONSTRAINT PK_MEGAG_PUSH_TOKENS PRIMARY KEY (ID),
    CONSTRAINT UK_MEGAG_PUSH_TOKENS UNIQUE (TOKEN),
    CONSTRAINT CK_MEGAG_PUSH_TOKENS_ATIVO CHECK (ATIVO IN ('S','N'))
);

CREATE SEQUENCE SEQ_MEGAG_PUSH_TOKENS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

