CREATE TABLE CONSINCO.MEGAG_TI_EQUIPAMENTOS (
    ID_EQUIPAMENTO    NUMBER(10)       NOT NULL,
    COD_PATRIMONIO    VARCHAR2(60)     NOT NULL,
    NOME_EQUIPAMENTO  VARCHAR2(120)    NOT NULL,
    TIPO              VARCHAR2(30)     NOT NULL,
    MARCA             VARCHAR2(80),
    MODELO            VARCHAR2(120),
    NUMERO_SERIE      VARCHAR2(120),
    STATUS            VARCHAR2(30)     DEFAULT 'EM_ESTOQUE' NOT NULL,
    CONDICAO          VARCHAR2(30)     DEFAULT 'BOM' NOT NULL,
    LOGIN_USUARIO     VARCHAR2(60),
    NOME_USUARIO      VARCHAR2(120),
    CPF_USUARIO       VARCHAR2(20),
    DEPARTAMENTO      VARCHAR2(120),
    LOCALIZACAO       VARCHAR2(120),
    DATA_AQUISICAO    DATE,
    GARANTIA_ATE      DATE,
    VALOR_AQUISICAO   NUMBER(14,2),
    FORNECEDOR        VARCHAR2(120),
    NOTA_FISCAL       VARCHAR2(60),
    IP_EQUIPAMENTO    VARCHAR2(45),
    ITENS_ENTREGUES   VARCHAR2(1000),
    OBSERVACAO        VARCHAR2(1000),
    ATIVO             CHAR(1)          DEFAULT 'S' NOT NULL,
    CRIADO_POR        VARCHAR2(60)     NOT NULL,
    CRIADO_EM         DATE             DEFAULT SYSDATE NOT NULL,
    ALTERADO_POR      VARCHAR2(60),
    ALTERADO_EM       DATE             DEFAULT SYSDATE,
    CONSTRAINT PK_MEGAG_TI_EQUIPAMENTOS PRIMARY KEY (ID_EQUIPAMENTO),
    CONSTRAINT UK_MEGAG_TI_EQUIP_PATRIMONIO UNIQUE (COD_PATRIMONIO),
    CONSTRAINT CK_MEGAG_TI_EQUIP_STATUS CHECK (STATUS IN ('EM_ESTOQUE', 'EM_USO', 'MANUTENCAO', 'BAIXADO')),
    CONSTRAINT CK_MEGAG_TI_EQUIP_COND CHECK (CONDICAO IN ('NOVO', 'BOM', 'REGULAR', 'CRITICO')),
    CONSTRAINT CK_MEGAG_TI_EQUIP_ATIVO CHECK (ATIVO IN ('S', 'N'))
);

CREATE INDEX CONSINCO.IDX_MEGAG_TI_EQUIP_STATUS ON CONSINCO.MEGAG_TI_EQUIPAMENTOS (STATUS);
CREATE INDEX CONSINCO.IDX_MEGAG_TI_EQUIP_TIPO ON CONSINCO.MEGAG_TI_EQUIPAMENTOS (TIPO);
CREATE INDEX CONSINCO.IDX_MEGAG_TI_EQUIP_USUARIO ON CONSINCO.MEGAG_TI_EQUIPAMENTOS (LOGIN_USUARIO);
CREATE INDEX CONSINCO.IDX_MEGAG_TI_EQUIP_GARANTIA ON CONSINCO.MEGAG_TI_EQUIPAMENTOS (GARANTIA_ATE);

CREATE SEQUENCE CONSINCO.SEQ_MEGAG_TI_EQUIPAMENTOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE CONSINCO.MEGAG_TI_EQUIP_HIST (
    ID_HISTORICO             NUMBER(10)      NOT NULL,
    ID_EQUIPAMENTO           NUMBER(10)      NOT NULL,
    TIPO_MOVIMENTACAO        VARCHAR2(30)    NOT NULL,
    STATUS_ANTERIOR          VARCHAR2(30),
    STATUS_NOVO              VARCHAR2(30),
    LOGIN_USUARIO_ANTERIOR   VARCHAR2(60),
    LOGIN_USUARIO_NOVO       VARCHAR2(60),
    LOCALIZACAO_ANTERIOR     VARCHAR2(120),
    LOCALIZACAO_NOVA         VARCHAR2(120),
    OBSERVACAO               VARCHAR2(1000),
    DESCRICAO_RESUMO         VARCHAR2(1000),
    CRIADO_POR               VARCHAR2(60)    NOT NULL,
    CRIADO_EM                DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_MEGAG_TI_EQUIP_HIST PRIMARY KEY (ID_HISTORICO),
    CONSTRAINT FK_MEGAG_TI_EQUIP_HIST FOREIGN KEY (ID_EQUIPAMENTO)
        REFERENCES CONSINCO.MEGAG_TI_EQUIPAMENTOS (ID_EQUIPAMENTO),
    CONSTRAINT CK_MEGAG_TI_EQUIP_HIST_TIPO CHECK (TIPO_MOVIMENTACAO IN ('CADASTRO', 'ATUALIZACAO'))
);

CREATE INDEX CONSINCO.IDX_MEGAG_TI_HIST_EQUIP ON CONSINCO.MEGAG_TI_EQUIP_HIST (ID_EQUIPAMENTO, CRIADO_EM);

CREATE SEQUENCE CONSINCO.SEQ_MEGAG_TI_EQUIP_HIST
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE CONSINCO.MEGAG_TI_TERMOS (
    ID_TERMO                  NUMBER(10)      NOT NULL,
    ID_EQUIPAMENTO            NUMBER(10)      NOT NULL,
    NOME_COLABORADOR          VARCHAR2(120)   NOT NULL,
    CPF_COLABORADOR           VARCHAR2(20),
    SETOR_COLABORADOR         VARCHAR2(120),
    CIDADE_EMISSAO            VARCHAR2(80),
    DATA_TERMO                DATE            DEFAULT SYSDATE NOT NULL,
    RESPONSAVEL_TI            VARCHAR2(120),
    STATUS_ASSINATURA         VARCHAR2(20)    DEFAULT 'PENDENTE' NOT NULL,
    ASSINATURA_COLABORADOR    CLOB,
    ASSINATURA_TI             CLOB,
    TERMO_HTML                CLOB,
    TERMO_HASH                VARCHAR2(64),
    CRIADO_POR                VARCHAR2(60)    NOT NULL,
    CRIADO_EM                 DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_MEGAG_TI_TERMOS PRIMARY KEY (ID_TERMO),
    CONSTRAINT FK_MEGAG_TI_TERMOS_EQUIP FOREIGN KEY (ID_EQUIPAMENTO)
        REFERENCES CONSINCO.MEGAG_TI_EQUIPAMENTOS (ID_EQUIPAMENTO),
    CONSTRAINT CK_MEGAG_TI_TERMOS_STATUS CHECK (STATUS_ASSINATURA IN ('PENDENTE', 'ASSINADO'))
);

CREATE INDEX CONSINCO.IDX_MEGAG_TI_TERMOS_EQUIP ON CONSINCO.MEGAG_TI_TERMOS (ID_EQUIPAMENTO, DATA_TERMO);

CREATE SEQUENCE CONSINCO.SEQ_MEGAG_TI_TERMOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE CONSINCO.MEGAG_ALMOX_SOLICITACOES (
    ID_SOLICITACAO           NUMBER(10)      NOT NULL,
    SOLICITANTE_NOME         VARCHAR2(120)   NOT NULL,
    SOLICITANTE_LOGIN        VARCHAR2(60),
    SOLICITANTE_CPF          VARCHAR2(20),
    SETOR_SOLICITANTE        VARCHAR2(120),
    CENTRO_CUSTO             VARCHAR2(30)    NOT NULL,
    SEQ_CENTRO_RESULTADO     NUMBER(10),
    FILIAL                   VARCHAR2(120)   NOT NULL,
    ITEM_SOLICITADO          VARCHAR2(200)   NOT NULL,
    ITENS_SOLICITADOS        VARCHAR2(2000)  NOT NULL,
    DESCRICAO_ITEM           VARCHAR2(500),
    UNIDADE_MEDIDA           VARCHAR2(30),
    QUANTIDADE               NUMBER(14,2)    NOT NULL,
    LOCAL_ENTREGA            VARCHAR2(120),
    DATA_NECESSIDADE         DATE,
    PRIORIDADE               VARCHAR2(20)    DEFAULT 'MEDIA' NOT NULL,
    STATUS                   VARCHAR2(20)    DEFAULT 'SOLICITADO' NOT NULL,
    JUSTIFICATIVA            VARCHAR2(1000)  NOT NULL,
    OBSERVACAO               VARCHAR2(1000),
    RESPONSAVEL_DESTINO      VARCHAR2(120),
    RESPONSAVEL_ALMOX        VARCHAR2(120),
    ASSINATURA_SOLICITANTE   CLOB,
    ASSINATURA_ALMOX         CLOB,
    CRIADO_POR               VARCHAR2(60)    NOT NULL,
    CRIADO_EM                DATE            DEFAULT SYSDATE NOT NULL,
    ALTERADO_POR             VARCHAR2(60),
    ALTERADO_EM              DATE            DEFAULT SYSDATE,
    CONSTRAINT PK_MEGAG_ALMOX_SOLIC PRIMARY KEY (ID_SOLICITACAO),
    CONSTRAINT CK_MEGAG_ALMOX_PRIORIDADE CHECK (PRIORIDADE IN ('BAIXA', 'MEDIA', 'ALTA', 'URGENTE')),
    CONSTRAINT CK_MEGAG_ALMOX_STATUS CHECK (STATUS IN ('SOLICITADO', 'EM_ANALISE', 'SEPARADO', 'ATENDIDO', 'CANCELADO'))
);

CREATE INDEX CONSINCO.IDX_MEGAG_ALMOX_STATUS ON CONSINCO.MEGAG_ALMOX_SOLICITACOES (STATUS, DATA_NECESSIDADE);

CREATE SEQUENCE CONSINCO.SEQ_MEGAG_ALMOX_SOLICITACOES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
