CREATE OR REPLACE PROCEDURE PRC_INS_MEGAG_DESP(
    p_USUARIOSOLICITANTE  IN MEGAG_DESP.USUARIOSOLICITANTE%TYPE,
    p_USUARIOAPROVADOR    IN MEGAG_DESP.USUARIOAPROVADOR%TYPE DEFAULT NULL,
    p_CODTIPODESPESA      IN MEGAG_DESP.CODTIPODESPESA%TYPE, --O PHP envia o ID escolhido(value)
    p_PAGO                IN MEGAG_DESP.PAGO%TYPE DEFAULT 'N',
    p_VLRRATDESPESA       IN MEGAG_DESP.VLRRATDESPESA%TYPE,
    p_FORNECEDOR          IN MEGAG_DESP.FORNECEDOR%TYPE DEFAULT NULL,
    p_NOMEARQUIVO         IN MEGAG_DESP.NOMEARQUIVO%TYPE DEFAULT NULL,
    p_OBSERVACAO          IN MEGAG_DESP.OBSERVACAO%TYPE DEFAULT NULL,
    p_SEQCENTRORESULTADO  IN MEGAG_DESP.SEQCENTRORESULTADO%TYPE,
    p_CENTROCUSTO         IN MEGAG_DESP.CENTROCUSTO%TYPE,
    p_STATUS              IN MEGAG_DESP.STATUS%TYPE DEFAULT 'LANCADO',
    p_CODDESPESA_OUT      OUT MEGAG_DESP.CODDESPESA%TYPE
)
IS
    -- Variável interna para guardar a descrição encontrada
    p_DESCRICAO MEGAG_DESP.DESCRICAO%TYPE;
BEGIN
    -- BUSCA AUTOMÁTICA: 
    -- A Procedure vai na tabela de tipos e pega a descrição correta
    SELECT DESCRICAO --label
      INTO p_DESCRICAO 
      FROM TB_TESTE_TIPO_DESPESA 
     WHERE CODTIPODESPESA = p_CODTIPODESPESA;

    -- INSERÇÃO:
    -- Agora usamos o p_CODTIPODESPESA (que veio do PHP) 
    -- e o p_DESCRICAO (que o banco acabou de achar)
    INSERT INTO MEGAG_DESP(
        USUARIOSOLICITANTE,
        USUARIOAPROVADOR,
        CODTIPODESPESA,
        DESCRICAO,
        PAGO,
        VLRRATDESPESA,
        FORNECEDOR,
        NOMEARQUIVO,
        OBSERVACAO,
        SEQCENTRORESULTADO,
        CENTROCUSTO,
        STATUS
    )
    VALUES(
        p_USUARIOSOLICITANTE,
        p_USUARIOAPROVADOR,
        p_CODTIPODESPESA,
        p_DESCRICAO, -- <--- Inserindo a descrição que o banco buscou
        p_PAGO,
        p_VLRRATDESPESA,
        p_FORNECEDOR,
        p_NOMEARQUIVO,
        p_OBSERVACAO,
        p_SEQCENTRORESULTADO,
        p_CENTROCUSTO,
        p_STATUS
    )
    RETURNING CODDESPESA INTO p_CODDESPESA_OUT;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        -- Caso o PHP envie um código que não existe na TB_TESTE_TIPO_DESPESA
        RAISE_APPLICATION_ERROR(-20001, 'Erro: O Tipo de Despesa informado não existe.');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20002, 'Erro ao inserir despesa: ' || SQLERRM);
END PRC_INS_MEGAG_DESP;
/

--SELECT 
CREATE OR REPLACE PROCEDURE PRC_LIST_MEGAG_DESP(
    p_USUARIOSOLICITANTE IN MEGAG_DESP.USUARIOSOLICITANTE%TYPE, -- Sempre obrigatório
    p_DESCRICAO          IN MEGAG_DESP.DESCRICAO%TYPE DEFAULT NULL,
    p_STATUS             IN MEGAG_DESP.STATUS%TYPE DEFAULT NULL, --'LANCADO','APROVACAO','APROVADO','REJEITADO'
    p_RESULT             OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN p_RESULT FOR
        SELECT *
          FROM MEGAG_DESP
         WHERE USUARIOSOLICITANTE = p_USUARIOSOLICITANTE
           -- Filtro de Descrição: Busca parcial e case-insensitive
           AND (p_DESCRICAO IS NULL OR UPPER(DESCRICAO) LIKE '%' || UPPER(p_DESCRICAO) || '%')
           -- Filtro de Status: Busca exata ('LANCADO','APROVACAO','APROVADO','REJEITADO')
           AND (p_STATUS IS NOT NULL OR STATUS = p_STATUS)
         ORDER BY DTAINCLUSAO DESC;
END PRC_LIST_MEGAG_DESP;
/

--UPDATE
CREATE OR REPLACE PROCEDURE PRC_UPD_MEGAG_DESP(
    p_CODDESPESA         IN MEGAG_DESP.CODDESPESA%TYPE,
    p_USUARIOSOLICITANTE IN MEGAG_DESP.USUARIOSOLICITANTE%TYPE,
    p_CODTIPODESPESA     IN MEGAG_DESP.CODTIPODESPESA%TYPE,
    p_DESCRICAO          IN MEGAG_DESP.DESCRICAO%TYPE,
    p_VLRRATDESPESA      IN MEGAG_DESP.VLRRATDESPESA%TYPE,
    p_FORNECEDOR         IN MEGAG_DESP.FORNECEDOR%TYPE,
    p_NOMEARQUIVO        IN MEGAG_DESP.NOMEARQUIVO%TYPE,
    p_OBSERVACAO         IN MEGAG_DESP.OBSERVACAO%TYPE,
    p_SEQCENTRORESULTADO IN MEGAG_DESP.SEQCENTRORESULTADO%TYPE,
    p_CENTROCUSTO        IN MEGAG_DESP.CENTROCUSTO%TYPE,
    p_STATUS             IN MEGAG_DESP.STATUS%TYPE
)
IS
BEGIN
    UPDATE MEGAG_DESP
       SET USUARIOSOLICITANTE = p_USUARIOSOLICITANTE,
    	   CODTIPODESPESA     = p_CODTIPODESPESA,
           DESCRICAO          = p_DESCRICAO,
           VLRRATDESPESA      = p_VLRRATDESPESA,
           FORNECEDOR         = p_FORNECEDOR,
           NOMEARQUIVO        = p_NOMEARQUIVO,
           OBSERVACAO         = p_OBSERVACAO,
           SEQCENTRORESULTADO = p_SEQCENTRORESULTADO,
           CENTROCUSTO        = p_CENTROCUSTO,
           STATUS             = p_STATUS,
           DTAALTERACAO       = SYSDATE
     WHERE CODDESPESA = p_CODDESPESA
     AND STATUS = 'LANCADO';

IF SQL%NOTFOUND THEN
        RAISE_APPLICATION_ERROR(-20001, 'ATUALIZAÇÃO NEGADA: Registro já passou pela aprovação do gestor.');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20002, 'Erro ao atualizar despesa: ' || SQLERRM);
END PRC_UPD_MEGAG_DESP;
/

--DELETE
CREATE OR REPLACE PROCEDURE PRC_DEL_MEGAG_DESP(
    p_CODDESPESA IN MEGAG_DESP.CODDESPESA%TYPE;
	p_DESCRICAO IN MEGAG_DESP.DESCRICAO%TYPE;
	p_USUARIOSOLICITANTE IN MEGAG_DESP.USUARIOSOLICITANTE%TYPE;
)
IS
BEGIN
	SELECT CODDESPESA 
		INTO p_CODDESPESA
	FROM MEGAG_DESP 
	WHERE CODDESPESA = p_CODDESPESA 
		AND USUARIOSOLICITANTE = p_USUARIOSOLICITANTE; 
		
	DELETE FROM MEGAG_DESP
		WHERE CODDESPESA = p_CODDESPESA;

END PRC_DEL_MEGAG_DESP;
/




