PROCEDURE PRC_INS_MEGAG_DESP_FORNECEDOR(
    p_NOMERAZAO      IN CONSINCO.GE_PESSOA.NOMERAZAO%TYPE,
    p_FANTASIA       IN CONSINCO.GE_PESSOA.FANTASIA%TYPE,
    p_PALAVRACHAVE   IN CONSINCO.GE_PESSOA.PALAVRACHAVE%TYPE,
    p_CEP            IN CONSINCO.GE_PESSOA.CEP%TYPE,
    p_FISICAJURIDICA IN CONSINCO.GE_PESSOA.FISICAJURIDICA%TYPE,
    p_SEXO           IN CONSINCO.GE_PESSOA.SEXO%TYPE,
    p_NROCGCCPF      IN CONSINCO.GE_PESSOA.NROCGCCPF%TYPE,
    p_DIGCGCCPF      IN CONSINCO.GE_PESSOA.DIGCGCCPF%TYPE,
    p_CIDADE         IN CONSINCO.GE_PESSOA.CIDADE%TYPE,
    p_UF             IN CONSINCO.GE_PESSOA.UF%TYPE,
    p_BAIRRO         IN CONSINCO.GE_PESSOA.BAIRRO%TYPE,
    p_LOGRADOURO     IN CONSINCO.GE_PESSOA.LOGRADOURO%TYPE,
    p_NROLOGRADOURO  IN CONSINCO.GE_PESSOA.NROLOGRADOURO%TYPE,
    p_FONEDDD1       IN CONSINCO.GE_PESSOA.FONEDDD1%TYPE,
    p_FONENRO1       IN CONSINCO.GE_PESSOA.FONENRO1%TYPE,
    p_EMAIL          IN CONSINCO.GE_PESSOA.EMAIL%TYPE,
    p_INSCRICAORG    IN CONSINCO.GE_PESSOA.INSCRICAORG%TYPE,
    p_DTAATIVACAO    IN CONSINCO.GE_PESSOA.DTAATIVACAO%TYPE,
    s_sfx            OUT VARCHAR2,
    s_ico            OUT VARCHAR2,
    s_tiporet        OUT VARCHAR2,
    s_msg            OUT VARCHAR2
) AS
    v_seqpessoa NUMBER;
BEGIN
    INSERT INTO CONSINCO.GE_PESSOA (NOMERAZAO, FANTASIA, NROCGCCPF, DIGCGCCPF)
    VALUES (p_NOMERAZAO, p_FANTASIA, p_NROCGCCPF, p_DIGCGCCPF)
    RETURNING SEQPESSOA INTO v_seqpessoa;
    
    COMMIT;
    s_sfx := 'success'; s_ico := 'success'; s_tiporet := 'S'; s_msg := 'Fornecedor cadastrado: ' || v_seqpessoa;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        s_sfx := 'error'; s_ico := 'danger'; s_tiporet := 'E'; s_msg := 'Erro: ' || SQLERRM;
END PRC_INS_MEGAG_DESP_FORNECEDOR;
/

PROCEDURE PRC_LIST_MEGAG_DESP_FORNECEDOR(
    p_cursor  OUT SYS_REFCURSOR,
    s_sfx     OUT VARCHAR2,
    s_ico     OUT VARCHAR2,
    s_tiporet OUT VARCHAR2,
    s_msg     OUT VARCHAR2
) AS
BEGIN
    OPEN p_cursor FOR SELECT * FROM CONSINCO.GE_PESSOA ORDER BY NOMERAZAO;
    s_sfx := 'success'; s_ico := 'success'; s_tiporet := 'S'; s_msg := 'OK';
END PRC_LIST_MEGAG_DESP_FORNECEDOR;
/
