CREATE OR REPLACE PACKAGE CONSINCO.PKG_MEGAG_DESP_CADASTRO IS

/* ==================================================
   FILE: AprovadoresCRUD.sql
================================================== */
PROCEDURE PRC_INS_MEGAG_DESP_APROVADORES(
    p_sequsuario           IN  CONSINCO.MEGAG_DESP_APROVADORES.SEQUSUARIO%TYPE,
    p_centrocusto          IN  CONSINCO.MEGAG_DESP_APROVADORES.CENTROCUSTO%TYPE,
    p_nome                 IN  CONSINCO.MEGAG_DESP_APROVADORES.NOME%TYPE,
    p_sequusuarioalt       IN  CONSINCO.MEGAG_DESP_APROVADORES.SEQUSUARIOALTERACAO%TYPE,
    p_dtaalteracao         IN  CONSINCO.MEGAG_DESP_APROVADORES.DTAALTERACAO%TYPE DEFAULT NULL,
    p_codgrupo             IN  CONSINCO.MEGAG_DESP_APROVADORES.CODGRUPO%TYPE,
    s_sfx                  OUT VARCHAR2,
    s_ico                  OUT VARCHAR2,
    s_tiporet              OUT VARCHAR2,
    s_msg                  OUT VARCHAR2
);

PROCEDURE PRC_LIST_MEGAG_DESP_APROVADORES(
    p_nome    IN  CONSINCO.GE_USUARIO.NOME%TYPE,
    p_cursor  OUT SYS_REFCURSOR,
    s_sfx     OUT VARCHAR2,
    s_ico     OUT VARCHAR2,
    s_tiporet OUT VARCHAR2,
    s_msg     OUT VARCHAR2
);

PROCEDURE PRC_UPD_MEGAG_DESP_APROVADORES(
    p_sequsuario           IN  CONSINCO.MEGAG_DESP_APROVADORES.SEQUSUARIO%TYPE,
    p_centrocusto          IN  CONSINCO.MEGAG_DESP_APROVADORES.CENTROCUSTO%TYPE,
    p_nome                 IN  CONSINCO.MEGAG_DESP_APROVADORES.NOME%TYPE,
    p_sequusuarioalt       IN  CONSINCO.MEGAG_DESP_APROVADORES.SEQUSUARIOALTERACAO%TYPE,
    p_dtaalteracao         IN  CONSINCO.MEGAG_DESP_APROVADORES.DTAALTERACAO%TYPE DEFAULT NULL,
    p_codgrupo             IN  CONSINCO.MEGAG_DESP_APROVADORES.CODGRUPO%TYPE,
    p_rows_affected        OUT NUMBER,
    s_sfx                  OUT VARCHAR2,
    s_ico                  OUT VARCHAR2,
    s_tiporet              OUT VARCHAR2,
    s_msg                  OUT VARCHAR2
);

PROCEDURE PRC_DEL_MEGAG_DESP_APROVADORES(
    p_nome    IN  VARCHAR2,
    s_sfx     OUT VARCHAR2,
    s_ico     OUT VARCHAR2,
    s_tiporet OUT VARCHAR2,
    s_msg     OUT VARCHAR2
);

PROCEDURE PRC_INS_MEGAG_DESP_CLONA_APROVADOR(
    p_sequsuario_origem  IN  CONSINCO.MEGAG_DESP_APROVADORES.SEQUSUARIO%TYPE,
    p_sequsuario_destino IN  CONSINCO.MEGAG_DESP_APROVADORES.SEQUSUARIO%TYPE,
    p_sequusuarioalt     IN  CONSINCO.MEGAG_DESP_APROVADORES.SEQUSUARIOALTERACAO%TYPE,
    s_sfx                OUT VARCHAR2,
    s_ico                OUT VARCHAR2,
    s_tiporet            OUT VARCHAR2,
    s_msg                OUT VARCHAR2
);

/* ==================================================
   FILE: DespesaCRUD.sql
================================================== */
PROCEDURE PRC_INS_MEGAG_DESP(
    p_USUARIOSOLICITANTE   IN  CONSINCO.MEGAG_DESP.USUARIOSOLICITANTE%TYPE,
    p_CODTIPODESPESA       IN  CONSINCO.MEGAG_DESP.CODTIPODESPESA%TYPE,
    p_PAGO                 IN  CONSINCO.MEGAG_DESP.PAGO%TYPE              DEFAULT 'N',
    p_VLRRATDESPESA        IN  CONSINCO.MEGAG_DESP.VLRRATDESPESA%TYPE,
    p_FORNECEDOR           IN  CONSINCO.MEGAG_DESP.FORNECEDOR%TYPE        DEFAULT NULL,
    p_NOMEARQUIVO          IN  CONSINCO.MEGAG_DESP.NOMEARQUIVO%TYPE       DEFAULT NULL,
    p_OBSERVACAO           IN  CONSINCO.MEGAG_DESP.OBSERVACAO%TYPE        DEFAULT NULL,
    p_CENTROCUSTO          IN  CONSINCO.MEGAG_DESP.CENTROCUSTO%TYPE,
    p_STATUS               IN  CONSINCO.MEGAG_DESP.STATUS%TYPE            DEFAULT 'LANCADO',
    p_DESCRICAOCENTROCUSTO IN  CONSINCO.MEGAG_DESP.DESCRICAOCENTROCUSTO%TYPE DEFAULT NULL,
    p_CODPOLITICA          IN  CONSINCO.MEGAG_DESP.CODPOLITICA%TYPE       DEFAULT NULL,
    p_DTAVENCIMENTO        IN  CONSINCO.MEGAG_DESP.DTAVENCIMENTO%TYPE     DEFAULT NULL,
    p_DTADESPESA           IN  CONSINCO.MEGAG_DESP.DTADESPESA%TYPE        DEFAULT NULL,
    p_CODDESPESA_OUT       OUT CONSINCO.MEGAG_DESP.CODDESPESA%TYPE,
    s_sfx                  OUT VARCHAR2,
    s_ico                  OUT VARCHAR2,
    s_tiporet              OUT VARCHAR2,
    s_msg                  OUT VARCHAR2
);

PROCEDURE PRC_LIST_MEGAG_DESP(
    p_CODDESPESA           IN  CONSINCO.MEGAG_DESP.CODDESPESA%TYPE,
    p_USUARIOSOLICITANTE   IN  CONSINCO.MEGAG_DESP.USUARIOSOLICITANTE%TYPE,
    p_DESCRICAO            IN  CONSINCO.MEGAG_DESP.DESCRICAO%TYPE         DEFAULT NULL,
    p_STATUS               IN  CONSINCO.MEGAG_DESP.STATUS%TYPE            DEFAULT NULL,
    p_RESULT               OUT SYS_REFCURSOR,
    s_sfx                  OUT VARCHAR2,
    s_ico                  OUT VARCHAR2,
    s_tiporet              OUT VARCHAR2,
    s_msg                  OUT VARCHAR2
);

PROCEDURE PRC_UPD_MEGAG_DESP(
    p_CODDESPESA           IN  CONSINCO.MEGAG_DESP.CODDESPESA%TYPE,
    p_USUARIOSOLICITANTE   IN  CONSINCO.MEGAG_DESP.USUARIOSOLICITANTE%TYPE,
    p_CODTIPODESPESA       IN  CONSINCO.MEGAG_DESP.CODTIPODESPESA%TYPE,
    p_DESCRICAO            IN  CONSINCO.MEGAG_DESP.DESCRICAO%TYPE,
    p_VLRRATDESPESA        IN  CONSINCO.MEGAG_DESP.VLRRATDESPESA%TYPE,
    p_FORNECEDOR           IN  CONSINCO.MEGAG_DESP.FORNECEDOR%TYPE,
    p_NOMEARQUIVO          IN  CONSINCO.MEGAG_DESP.NOMEARQUIVO%TYPE,
    p_OBSERVACAO           IN  CONSINCO.MEGAG_DESP.OBSERVACAO%TYPE,
    p_CENTROCUSTO          IN  CONSINCO.MEGAG_DESP.CENTROCUSTO%TYPE,
    p_STATUS               IN  CONSINCO.MEGAG_DESP.STATUS%TYPE,
    p_DESCRICAOCENTROCUSTO IN  CONSINCO.MEGAG_DESP.DESCRICAOCENTROCUSTO%TYPE,
    p_DTAVENCIMENTO        IN  CONSINCO.MEGAG_DESP.DTAVENCIMENTO%TYPE     DEFAULT NULL,
    p_DTADESPESA           IN  CONSINCO.MEGAG_DESP.DTADESPESA%TYPE        DEFAULT NULL,
    s_sfx                  OUT VARCHAR2,
    s_ico                  OUT VARCHAR2,
    s_tiporet              OUT VARCHAR2,
    s_msg                  OUT VARCHAR2
);

PROCEDURE PRC_DEL_MEGAG_DESP(
    p_CODDESPESA         IN  CONSINCO.MEGAG_DESP.CODDESPESA%TYPE,
    p_USUARIOSOLICITANTE IN  CONSINCO.MEGAG_DESP.USUARIOSOLICITANTE%TYPE,
    s_sfx                OUT VARCHAR2,
    s_ico                OUT VARCHAR2,
    s_tiporet            OUT VARCHAR2,
    s_msg                OUT VARCHAR2
);

/* ==================================================
   FILE: TipoDespesaCRUD.sql
================================================== */
PROCEDURE PRC_INS_MEGAG_DESP_TIPO(
    p_DESCRICAO IN  CONSINCO.MEGAG_DESP_TIPO.DESCRICAO%TYPE,
    s_sfx       OUT VARCHAR2,
    s_ico       OUT VARCHAR2,
    s_tiporet   OUT VARCHAR2,
    s_msg       OUT VARCHAR2
);

PROCEDURE PRC_LIST_MEGAG_DESP_TIPO(
    p_CODTIPODESPESA IN  CONSINCO.MEGAG_DESP_TIPO.CODTIPODESPESA%TYPE,
    p_DESCRICAO      IN  CONSINCO.MEGAG_DESP_TIPO.DESCRICAO%TYPE,
    p_RESULT         OUT SYS_REFCURSOR,
    s_sfx            OUT VARCHAR2,
    s_ico            OUT VARCHAR2,
    s_tiporet        OUT VARCHAR2,
    s_msg            OUT VARCHAR2
);

PROCEDURE PRC_UPD_MEGAG_DESP_TIPO(
    p_CODTIPODESPESA IN  CONSINCO.MEGAG_DESP_TIPO.CODTIPODESPESA%TYPE,
    p_DESCRICAO      IN  CONSINCO.MEGAG_DESP_TIPO.DESCRICAO%TYPE,
    s_sfx            OUT VARCHAR2,
    s_ico            OUT VARCHAR2,
    s_tiporet        OUT VARCHAR2,
    s_msg            OUT VARCHAR2
);

PROCEDURE PRC_DEL_MEGAG_DESP_TIPO(
    p_CODTIPODESPESA IN  CONSINCO.MEGAG_DESP_TIPO.CODTIPODESPESA%TYPE,
    s_sfx            OUT VARCHAR2,
    s_ico            OUT VARCHAR2,
    s_tiporet        OUT VARCHAR2,
    s_msg            OUT VARCHAR2
);

/* ==================================================
   FILE: CentroCustoDespesaCRUD.sql
================================================== */
PROCEDURE PRC_INS_MEGAG_DESP_CENTRO_CUSTO(
    p_centrocusto        IN  CONSINCO.ABA_CENTRORESULTADO.CENTRORESULTADO%TYPE,
    p_coddespesa         IN  CONSINCO.MEGAG_DESP.CODDESPESA%TYPE,
    p_usuariosolicitante IN  CONSINCO.MEGAG_DESP.USUARIOSOLICITANTE%TYPE,
    s_sfx                OUT VARCHAR2,
    s_ico                OUT VARCHAR2,
    s_tiporet            OUT VARCHAR2,
    s_msg                OUT VARCHAR2
);

PROCEDURE PRC_LIST_MEGAG_DESP_CENTRO_CUSTO(
    p_cursor  OUT SYS_REFCURSOR,
    s_sfx     OUT VARCHAR2,
    s_ico     OUT VARCHAR2,
    s_tiporet OUT VARCHAR2,
    s_msg     OUT VARCHAR2
);

PROCEDURE PRC_UPD_MEGAG_DESP_CENTRO_CUSTO(
    p_centrocusto_atual        IN  CONSINCO.MEGAG_DESP.CENTROCUSTO%TYPE,
    p_centrocusto_novo         IN  CONSINCO.MEGAG_DESP.CENTROCUSTO%TYPE,
    p_descricao_nova           IN  CONSINCO.MEGAG_DESP.DESCRICAOCENTROCUSTO%TYPE,
    p_coddespesa               IN  CONSINCO.MEGAG_DESP.CODDESPESA%TYPE,
    p_usuariosolicitante       IN  CONSINCO.MEGAG_DESP.USUARIOSOLICITANTE%TYPE,
    s_sfx                      OUT VARCHAR2,
    s_ico                      OUT VARCHAR2,
    s_tiporet                  OUT VARCHAR2,
    s_msg                      OUT VARCHAR2
);

PROCEDURE PRC_INS_MEGAG_DESP_APROVACAO(
    p_coddespesa IN  CONSINCO.MEGAG_DESP.CODDESPESA%TYPE,
    s_sfx        OUT VARCHAR2,
    s_ico        OUT VARCHAR2,
    s_tiporet    OUT VARCHAR2,
    s_msg        OUT VARCHAR2
);

PROCEDURE PRC_LIST_MEGAG_DESP_APROVACAO(
    p_sequsuario IN  CONSINCO.MEGAG_DESP_APROVADORES.SEQUSUARIO%TYPE,
    p_cursor     OUT SYS_REFCURSOR,
    s_sfx        OUT VARCHAR2,
    s_ico        OUT VARCHAR2,
    s_tiporet    OUT VARCHAR2,
    s_msg        OUT VARCHAR2
);

PROCEDURE PRC_UPD_MEGAG_DESP_APROVACAO(
    p_coddespesa  IN  CONSINCO.MEGAG_DESP.CODDESPESA%TYPE,
    p_sequsuario  IN  CONSINCO.MEGAG_DESP_APROVADORES.SEQUSUARIO%TYPE,
    p_status      IN  CONSINCO.MEGAG_DESP_APROVACAO.STATUS%TYPE,
    p_pago        IN  CONSINCO.MEGAG_DESP.PAGO%TYPE,
    p_observacao  IN  CONSINCO.MEGAG_DESP.OBSERVACAO%TYPE,
    s_sfx         OUT VARCHAR2,
    s_ico         OUT VARCHAR2,
    s_tiporet     OUT VARCHAR2,
    s_msg         OUT VARCHAR2
);

/* ==================================================
   FILE: ArquivoCRUD.sql
================================================== */
PROCEDURE PRC_INS_MEGAG_DESP_ARQUIVO(
    p_CODDESPESA     IN  CONSINCO.MEGAG_DESP_ARQUIVO.CODDESPESA%TYPE,
    p_NOMEARQUIVO    IN  CONSINCO.MEGAG_DESP_ARQUIVO.NOMEARQUIVO%TYPE,
    p_TIPOARQUIVO    IN  CONSINCO.MEGAG_DESP_ARQUIVO.TIPOARQUIVO%TYPE DEFAULT NULL,
    p_CODARQUIVO_OUT OUT CONSINCO.MEGAG_DESP_ARQUIVO.CODARQUIVO%TYPE,
    s_sfx            OUT VARCHAR2,
    s_ico            OUT VARCHAR2,
    s_tiporet        OUT VARCHAR2,
    s_msg            OUT VARCHAR2
);

PROCEDURE PRC_SEL_MEGAG_DESP_ARQUIVO(
    p_CODARQUIVO IN  CONSINCO.MEGAG_DESP_ARQUIVO.CODARQUIVO%TYPE DEFAULT NULL,
    p_CODDESPESA IN  CONSINCO.MEGAG_DESP_ARQUIVO.CODDESPESA%TYPE DEFAULT NULL,
    p_RESULT     OUT SYS_REFCURSOR,
    s_sfx        OUT VARCHAR2,
    s_ico        OUT VARCHAR2,
    s_tiporet    OUT VARCHAR2,
    s_msg        OUT VARCHAR2
);

PROCEDURE PRC_UPD_MEGAG_DESP_ARQUIVO(
    p_CODARQUIVO  IN  CONSINCO.MEGAG_DESP_ARQUIVO.CODARQUIVO%TYPE,
    p_NOMEARQUIVO IN  CONSINCO.MEGAG_DESP_ARQUIVO.NOMEARQUIVO%TYPE,
    p_TIPOARQUIVO IN  CONSINCO.MEGAG_DESP_ARQUIVO.TIPOARQUIVO%TYPE DEFAULT NULL,
    s_sfx         OUT VARCHAR2,
    s_ico         OUT VARCHAR2,
    s_tiporet     OUT VARCHAR2,
    s_msg         OUT VARCHAR2
);

PROCEDURE PRC_DEL_MEGAG_DESP_ARQUIVO(
    p_CODARQUIVO IN  CONSINCO.MEGAG_DESP_ARQUIVO.CODARQUIVO%TYPE,
    s_sfx        OUT VARCHAR2,
    s_ico        OUT VARCHAR2,
    s_tiporet    OUT VARCHAR2,
    s_msg        OUT VARCHAR2
);

/* ==================================================
   FILE: PoliticaCCCRUD.sql
================================================== */
PROCEDURE PRC_INS_MEGAG_DESP_POLIT_CENTRO_CUSTO(
    p_codpolitica      IN  CONSINCO.MEGAG_DESP_POLIT_CENTRO_CUSTO.CODPOLITICA%TYPE,
    p_codgrupo         IN  CONSINCO.MEGAG_DESP_POLIT_CENTRO_CUSTO.CODGRUPO%TYPE,
    p_sequsuario       IN  CONSINCO.MEGAG_DESP_POLIT_CENTRO_CUSTO.SEQUSUARIO%TYPE,
    p_centrocusto      IN  CONSINCO.MEGAG_DESP_POLIT_CENTRO_CUSTO.CENTROCUSTO%TYPE,
    p_nivel_aprovacao  IN  CONSINCO.MEGAG_DESP_POLIT_CENTRO_CUSTO.NIVEL_APROVACAO%TYPE,
    p_descricao        IN  CONSINCO.MEGAG_DESP_POLIT_CENTRO_CUSTO.DESCRICAO%TYPE DEFAULT NULL,
    p_codpolit_cc      OUT CONSINCO.MEGAG_DESP_POLIT_CENTRO_CUSTO.CODPOLIT_CC%TYPE,
    s_sfx              OUT VARCHAR2,
    s_ico              OUT VARCHAR2,
    s_tiporet          OUT VARCHAR2,
    s_msg              OUT VARCHAR2
);

PROCEDURE PRC_LIST_MEGAG_DESP_POLIT_CENTRO_CUSTO(
    p_codpolitica IN  CONSINCO.MEGAG_DESP_POLIT_CENTRO_CUSTO.CODPOLITICA%TYPE DEFAULT NULL,
    p_cursor      OUT SYS_REFCURSOR,
    s_sfx         OUT VARCHAR2,
    s_ico         OUT VARCHAR2,
    s_tiporet     OUT VARCHAR2,
    s_msg         OUT VARCHAR2
);

PROCEDURE PRC_UPD_MEGAG_DESP_POLIT_CENTRO_CUSTO(
    p_codpolit_cc      IN  CONSINCO.MEGAG_DESP_POLIT_CENTRO_CUSTO.CODPOLIT_CC%TYPE,
    p_codgrupo         IN  CONSINCO.MEGAG_DESP_POLIT_CENTRO_CUSTO.CODGRUPO%TYPE,
    p_sequsuario       IN  CONSINCO.MEGAG_DESP_POLIT_CENTRO_CUSTO.SEQUSUARIO%TYPE,
    p_centrocusto      IN  CONSINCO.MEGAG_DESP_POLIT_CENTRO_CUSTO.CENTROCUSTO%TYPE,
    p_nivel_aprovacao  IN  CONSINCO.MEGAG_DESP_POLIT_CENTRO_CUSTO.NIVEL_APROVACAO%TYPE,
    p_descricao        IN  CONSINCO.MEGAG_DESP_POLIT_CENTRO_CUSTO.DESCRICAO%TYPE DEFAULT NULL,
    s_sfx              OUT VARCHAR2,
    s_ico              OUT VARCHAR2,
    s_tiporet          OUT VARCHAR2,
    s_msg              OUT VARCHAR2
);

PROCEDURE PRC_DEL_MEGAG_DESP_POLIT_CENTRO_CUSTO(
    p_codpolit_cc IN  CONSINCO.MEGAG_DESP_POLIT_CENTRO_CUSTO.CODPOLIT_CC%TYPE,
    s_sfx         OUT VARCHAR2,
    s_ico         OUT VARCHAR2,
    s_tiporet     OUT VARCHAR2,
    s_msg         OUT VARCHAR2
);

/* ==================================================
   FILE: GrupoCRUD.sql
================================================== */
PROCEDURE PRC_INS_MEGAG_DESP_GRUPO(
    p_nomegrupo    IN  CONSINCO.MEGAG_DESP_GRUPO.NOMEGRUPO%TYPE,
    p_dtainclusao  IN  CONSINCO.MEGAG_DESP_GRUPO.DTAINCLUSAO%TYPE,
    p_dtaalteracao IN  CONSINCO.MEGAG_DESP_GRUPO.DTAALTERACAO%TYPE,
    s_sfx          OUT VARCHAR2,
    s_ico          OUT VARCHAR2,
    s_tiporet      OUT VARCHAR2,
    s_msg          OUT VARCHAR2
);

PROCEDURE PRC_LIST_MEGAG_DESP_GRUPO(
    p_cursor  OUT SYS_REFCURSOR,
    s_sfx     OUT VARCHAR2,
    s_ico     OUT VARCHAR2,
    s_tiporet OUT VARCHAR2,
    s_msg     OUT VARCHAR2
);

PROCEDURE PRC_UPD_MEGAG_DESP_GRUPO(
    p_codgrupo  IN  CONSINCO.MEGAG_DESP_GRUPO.CODGRUPO%TYPE,
    p_nomegrupo IN  CONSINCO.MEGAG_DESP_GRUPO.NOMEGRUPO%TYPE,
    s_sfx       OUT VARCHAR2,
    s_ico       OUT VARCHAR2,
    s_tiporet   OUT VARCHAR2,
    s_msg       OUT VARCHAR2
);

PROCEDURE PRC_DEL_MEGAG_DESP_GRUPO(
    p_codgrupo IN  CONSINCO.MEGAG_DESP_GRUPO.CODGRUPO%TYPE,
    s_sfx      OUT VARCHAR2,
    s_ico      OUT VARCHAR2,
    s_tiporet  OUT VARCHAR2,
    s_msg      OUT VARCHAR2
);

/* ==================================================
   FILE: RateioCRUD.sql
================================================== */
PROCEDURE PRC_INS_MEGAG_DESP_RATEIO(
    p_coddespesa         IN  CONSINCO.MEGAG_DESP_RATEIO.CODDESPESA%TYPE,
    p_centrocusto        IN  CONSINCO.MEGAG_DESP_RATEIO.CENTROCUSTO%TYPE,
    p_valorrateio        IN  CONSINCO.MEGAG_DESP_RATEIO.VALORRATEIO%TYPE,
    p_codrateio          OUT NUMBER,
    s_sfx                OUT VARCHAR2,
    s_ico                OUT VARCHAR2,
    s_tiporet            OUT VARCHAR2,
    s_msg                OUT VARCHAR2
);

PROCEDURE PRC_LIST_MEGAG_DESP_RATEIO(
    p_coddespesa IN  CONSINCO.MEGAG_DESP_RATEIO.CODDESPESA%TYPE,
    p_cursor     OUT SYS_REFCURSOR,
    s_sfx        OUT VARCHAR2,
    s_ico        OUT VARCHAR2,
    s_tiporet    OUT VARCHAR2,
    s_msg        OUT VARCHAR2
);

PROCEDURE PRC_UPD_MEGAG_DESP_RATEIO(
    p_codrateio   IN  CONSINCO.MEGAG_DESP_RATEIO.CODRATEIO%TYPE,
    p_valorrateio IN  CONSINCO.MEGAG_DESP_RATEIO.VALORRATEIO%TYPE,
    s_sfx         OUT VARCHAR2,
    s_ico         OUT VARCHAR2,
    s_tiporet     OUT VARCHAR2,
    s_msg         OUT VARCHAR2
);

PROCEDURE PRC_DEL_MEGAG_DESP_RATEIO(
    p_codrateio IN  CONSINCO.MEGAG_DESP_RATEIO.CODRATEIO%TYPE,
    s_sfx       OUT VARCHAR2,
    s_ico       OUT VARCHAR2,
    s_tiporet   OUT VARCHAR2,
    s_msg       OUT VARCHAR2
);

/* ==================================================
   FILE: FornecedorCRUD.sql
================================================== */
PROCEDURE PRC_INS_MEGAG_DESP_FORNECEDOR(
    p_NOMERAZAO      IN CONSINCO.GE_PESSOA.NOMERAZAO%TYPE,
    p_FANTASIA       IN CONSINCO.GE_PESSOA.FANTASIA%TYPE,
    p_PALAVRACHAVE   IN CONSINCO.GE_PESSOA.PALAVRACHAVE%TYPE,
    p_CEP            IN CONSINCO.GE_PESSOA.CEP%TYPE,
    p_FISICAJURIDICA IN CONSINCO.GE_PESSOA.FISICAJURIDICA%TYPE,
    p_SEXO           IN CONSINCO.GE_PESSOA.SEXO%TYPE,
    p_NROCGCCPF      IN CONSINCO.GE_PESSOA.NROCGCCPF%TYPE,
    p_DIGCGCCPF      IN CONSINCO.GE_PESSOA.DIGCGCCPF%TYPE,
    p_CIDADE         IN CONSINCO.GE_PESSOA.CIDADE%TYPE,
    p_UF             IN CONSINCO.GE_PESSOA.UF%TYPE,
    p_BAIRRO         IN CONSINCO.GE_PESSOA.BAIRRO%TYPE,
    p_LOGRADOURO     IN CONSINCO.GE_PESSOA.LOGRADOURO%TYPE,
    p_NROLOGRADOURO  IN CONSINCO.GE_PESSOA.NROLOGRADOURO%TYPE,
    p_FONEDDD1       IN CONSINCO.GE_PESSOA.FONEDDD1%TYPE,
    p_FONENRO1       IN CONSINCO.GE_PESSOA.FONENRO1%TYPE,
    p_EMAIL          IN CONSINCO.GE_PESSOA.EMAIL%TYPE,
    p_INSCRICAORG    IN CONSINCO.GE_PESSOA.INSCRICAORG%TYPE,
    p_DTAATIVACAO    IN CONSINCO.GE_PESSOA.DTAATIVACAO%TYPE,
    s_sfx            OUT VARCHAR2,
    s_ico            OUT VARCHAR2,
    s_tiporet        OUT VARCHAR2,
    s_msg            OUT VARCHAR2
);

PROCEDURE PRC_LIST_MEGAG_DESP_FORNECEDOR(
    p_cursor  OUT SYS_REFCURSOR,
    s_sfx     OUT VARCHAR2,
    s_ico     OUT VARCHAR2,
    s_tiporet OUT VARCHAR2,
    s_msg     OUT VARCHAR2
);

/* ==================================================
   FILE: PoliticaMaeCRUD.sql
================================================== */
PROCEDURE PRC_INS_MEGAG_DESP_POLITICA(
    p_descricao         IN  CONSINCO.MEGAG_DESP_POLITICA.DESCRICAO%TYPE,
    p_codgrupo          IN  CONSINCO.MEGAG_DESP_POLIT_CENTRO_CUSTO.CODGRUPO%TYPE,
    p_sequsuario        IN  CONSINCO.MEGAG_DESP_POLIT_CENTRO_CUSTO.SEQUSUARIO%TYPE,
    p_centrocusto       IN  CONSINCO.MEGAG_DESP_POLIT_CENTRO_CUSTO.CENTROCUSTO%TYPE,
    p_nivel_aprovacao   IN  CONSINCO.MEGAG_DESP_POLIT_CENTRO_CUSTO.NIVEL_APROVACAO%TYPE,
    p_descricao_vinculo IN  CONSINCO.MEGAG_DESP_POLIT_CENTRO_CUSTO.DESCRICAO%TYPE DEFAULT NULL,
    p_codpolitica       OUT CONSINCO.MEGAG_DESP_POLITICA.CODPOLITICA%TYPE,
    p_codpolit_cc       OUT CONSINCO.MEGAG_DESP_POLIT_CENTRO_CUSTO.CODPOLIT_CC%TYPE,
    s_sfx               OUT VARCHAR2,
    s_ico               OUT VARCHAR2,
    s_tiporet           OUT VARCHAR2,
    s_msg               OUT VARCHAR2
);

PROCEDURE PRC_LIST_MEGAG_DESP_POLITICA(
    p_codpolitica IN  CONSINCO.MEGAG_DESP_POLITICA.CODPOLITICA%TYPE DEFAULT NULL,
    p_cursor      OUT SYS_REFCURSOR,
    s_sfx         OUT VARCHAR2,
    s_ico         OUT VARCHAR2,
    s_tiporet     OUT VARCHAR2,
    s_msg     OUT VARCHAR2
);

PROCEDURE PRC_UPD_MEGAG_DESP_POLITICA(
    p_codpolitica IN  CONSINCO.MEGAG_DESP_POLITICA.CODPOLITICA%TYPE,
    p_descricao   IN  CONSINCO.MEGAG_DESP_POLITICA.DESCRICAO%TYPE,
    s_sfx         OUT VARCHAR2,
    s_ico         OUT VARCHAR2,
    s_tiporet     OUT VARCHAR2,
    s_msg         OUT VARCHAR2
);

PROCEDURE PRC_DEL_MEGAG_DESP_POLITICA(
    p_codpolitica IN  CONSINCO.MEGAG_DESP_POLITICA.CODPOLITICA%TYPE,
    s_sfx         OUT VARCHAR2,
    s_ico         OUT VARCHAR2,
    s_tiporet     OUT VARCHAR2,
    s_msg         OUT VARCHAR2
);

END PKG_MEGAG_DESP_CADASTRO;
/
