CREATE OR REPLACE PACKAGE CONSINCO.PKG_MEGAG_DESP_CADASTRO IS

PROCEDURE PRC_INS_MEGAG_DESP_APROVADORES (
    p_sequsuario           IN MEGAG_DESP_APROVADORES.SEQUSUARIO%TYPE,
    p_centrocusto          IN MEGAG_DESP_APROVADORES.CENTROCUSTO%TYPE,
    p_seqcentroresultado   IN MEGAG_DESP_APROVADORES.SEQCENTRORESULTADO%TYPE,
    p_nome       		   IN MEGAG_DESP_APROVADORES.NOME%TYPE,
    p_sequusuarioalt       IN MEGAG_DESP_APROVADORES.SEQUSUARIOALTERACAO%TYPE,
    p_dtaalteracao         IN MEGAG_DESP_APROVADORES.DTAALTERACAO%TYPE DEFAULT NULL,
	p_codgrupo			   IN MEGAG_DESP_APROVADORES.CODGRUPO%TYPE
);

PROCEDURE PRC_LIST_MEGAG_DESP_APROVADORES (
    p_nome IN GE_USUARIO.NOME%TYPE,
    p_cursor OUT SYS_REFCURSOR
);

PROCEDURE PRC_UPD_MEGAG_DESP_APROVADORES (
    p_sequsuario           IN MEGAG_DESP_APROVADORES.SEQUSUARIO%TYPE,
    p_centrocusto          IN MEGAG_DESP_APROVADORES.CENTROCUSTO%TYPE,
    p_seqcentroresultado   IN MEGAG_DESP_APROVADORES.SEQCENTRORESULTADO%TYPE,
    p_nome                 IN MEGAG_DESP_APROVADORES.NOME%TYPE,
    p_sequusuarioalt       IN MEGAG_DESP_APROVADORES.SEQUSUARIOALTERACAO%TYPE,
    p_dtaalteracao         IN MEGAG_DESP_APROVADORES.DTAALTERACAO%TYPE DEFAULT NULL,
	p_codgrupo			   IN MEGAG_DESP_APROVADORES.CODGRUPO%TYPE,
    p_rows_affected        OUT NUMBER
);

PROCEDURE PRC_DEL_MEGAG_DESP_APROVADORES (
    p_nome IN VARCHAR2
);

PROCEDURE PRC_INS_MEGAG_DESP (
    p_USUARIOSOLICITANTE  	IN MEGAG_DESP.USUARIOSOLICITANTE%TYPE,
    p_CODTIPODESPESA      	IN MEGAG_DESP.CODTIPODESPESA%TYPE, --O PHP envia o ID escolhido(value)
    p_PAGO                	IN MEGAG_DESP.PAGO%TYPE DEFAULT 'N',
    p_VLRRATDESPESA       	IN MEGAG_DESP.VLRRATDESPESA%TYPE,
    p_FORNECEDOR          	IN MEGAG_DESP.FORNECEDOR%TYPE DEFAULT NULL,
    p_NOMEARQUIVO         	IN MEGAG_DESP.NOMEARQUIVO%TYPE DEFAULT NULL,
    p_OBSERVACAO          	IN MEGAG_DESP.OBSERVACAO%TYPE DEFAULT NULL,
    p_SEQCENTRORESULTADO  	IN MEGAG_DESP.SEQCENTRORESULTADO%TYPE,
    p_CENTROCUSTO         	IN MEGAG_DESP.CENTROCUSTO%TYPE,
    p_STATUS              	IN MEGAG_DESP.STATUS%TYPE DEFAULT 'LANCADO',
	p_DESCRICAOCENTROCUSTO	IN MEGAG_DESP.DESCRICAOCENTROCUSTO%TYPE DEFAULT NULL,
	p_CODPOLITICA			IN MEGAG_DESP.CODPOLITICA%TYPE DEFAULT NULL,
	p_DTAVENCIMENTO			IN MEGAG_DESP.DTAVENCIMENTO%TYPE DEFAULT NULL,
	p_DTADESPESA			IN MEGAG_DESP.DTADESPESA%TYPE DEFAULT NULL,
    p_CODDESPESA_OUT      	OUT MEGAG_DESP.CODDESPESA%TYPE
);

PROCEDURE PRC_LIST_MEGAG_DESP (
	p_CODDESPESA		 IN MEGAG_DESP.CODDESPESA%TYPE,
    p_USUARIOSOLICITANTE IN MEGAG_DESP.USUARIOSOLICITANTE%TYPE, -- Sempre obrigatório
    p_DESCRICAO          IN MEGAG_DESP.DESCRICAO%TYPE DEFAULT NULL,
    p_STATUS             IN MEGAG_DESP.STATUS%TYPE DEFAULT NULL, --'LANCADO','APROVACAO','APROVADO','REJEITADO'
    p_RESULT             OUT SYS_REFCURSOR
);

PROCEDURE PRC_UPD_MEGAG_DESP (
    p_CODDESPESA         	IN MEGAG_DESP.CODDESPESA%TYPE,
    p_USUARIOSOLICITANTE 	IN MEGAG_DESP.USUARIOSOLICITANTE%TYPE,
    p_CODTIPODESPESA     	IN MEGAG_DESP.CODTIPODESPESA%TYPE,
    p_DESCRICAO          	IN MEGAG_DESP.DESCRICAO%TYPE,
    p_VLRRATDESPESA      	IN MEGAG_DESP.VLRRATDESPESA%TYPE,
    p_FORNECEDOR         	IN MEGAG_DESP.FORNECEDOR%TYPE,
    p_NOMEARQUIVO        	IN MEGAG_DESP.NOMEARQUIVO%TYPE,
    p_OBSERVACAO         	IN MEGAG_DESP.OBSERVACAO%TYPE,
    p_SEQCENTRORESULTADO 	IN MEGAG_DESP.SEQCENTRORESULTADO%TYPE,
    p_CENTROCUSTO        	IN MEGAG_DESP.CENTROCUSTO%TYPE,
    p_STATUS             	IN MEGAG_DESP.STATUS%TYPE,
	p_DESCRICAOCENTROCUSTO  IN MEGAG_DESP.DESCRICAOCENTROCUSTO%TYPE,
	p_DTAVENCIMENTO			IN MEGAG_DESP.DTAVENCIMENTO%TYPE DEFAULT NULL,
	p_DTADESPESA			IN MEGAG_DESP.DTADESPESA%TYPE DEFAULT NULL
);

PROCEDURE PRC_DEL_MEGAG_DESP (
    p_CODDESPESA IN MEGAG_DESP.CODDESPESA%TYPE,
	p_USUARIOSOLICITANTE IN MEGAG_DESP.USUARIOSOLICITANTE%TYPE
);

PROCEDURE PRC_INS_MEGAG_DESP_TIPO (
    p_DESCRICAO IN MEGAG_DESP_TIPO.DESCRICAO%TYPE
);

PROCEDURE PRC_LIST_MEGAG_DESP_TIPO (
    p_CODTIPODESPESA IN  MEGAG_DESP_TIPO.CODTIPODESPESA%TYPE,
    p_DESCRICAO      IN  MEGAG_DESP_TIPO.DESCRICAO%TYPE, 
    p_RESULT         OUT SYS_REFCURSOR
);

PROCEDURE PRC_UPD_MEGAG_DESP_TIPO (
    p_CODTIPODESPESA IN MEGAG_DESP_TIPO.CODTIPODESPESA%TYPE,
    p_DESCRICAO      IN MEGAG_DESP_TIPO.DESCRICAO%TYPE
);

PROCEDURE PRC_DEL_MEGAG_DESP_TIPO (
    p_CODTIPODESPESA IN MEGAG_DESP_TIPO.CODTIPODESPESA%TYPE
);

PROCEDURE PRC_INS_MEGAG_DESP_CENTRO_CUSTO (
    p_centrocusto        IN ABA_CENTRORESULTADO.CENTRORESULTADO%TYPE,
    p_coddespesa         IN MEGAG_DESP.CODDESPESA%TYPE,
    p_usuariosolicitante IN MEGAG_DESP.USUARIOSOLICITANTE%TYPE
);

PROCEDURE PRC_LIST_MEGAG_DESP_CENTRO_CUSTO (
    p_cursor OUT SYS_REFCURSOR
);

PROCEDURE PRC_UPD_MEGAG_DESP_CENTRO_CUSTO (
    p_centrocusto_atual        IN MEGAG_DESP.CENTROCUSTO%TYPE,
    p_seqcentroresultado_atual IN MEGAG_DESP.SEQCENTRORESULTADO%TYPE,
    p_centrocusto_novo         IN MEGAG_DESP.CENTROCUSTO%TYPE,
    p_seqcentroresultado_novo  IN MEGAG_DESP.SEQCENTRORESULTADO%TYPE,
    p_descricao_nova           IN MEGAG_DESP.DESCRICAOCENTROCUSTO%TYPE,
    p_coddespesa               IN MEGAG_DESP.CODDESPESA%TYPE,
    p_usuariosolicitante       IN MEGAG_DESP.USUARIOSOLICITANTE%TYPE
);

/*
PROCEDURE PRC_DEL_MEGAG_DESP_CENTRO_CUSTO (
    p_centrocusto        IN MEGAG_DESP.CENTROCUSTO%TYPE,
    p_seqcentroresultado IN MEGAG_DESP.SEQCENTRORESULTADO%TYPE
);
*/
PROCEDURE PRC_INS_MEGAG_DESP_APROVACAO (
    p_coddespesa IN MEGAG_DESP.CODDESPESA%TYPE
);

PROCEDURE PRC_LIST_MEGAG_DESP_APROVACAO (
    p_sequsuario  IN MEGAG_DESP_APROVADORES.SEQUSUARIO%TYPE, -- Usuário logado no sistema no momento.
    p_cursor      OUT SYS_REFCURSOR
);

PROCEDURE PRC_UPD_MEGAG_DESP_APROVACAO(
    p_coddespesa     IN MEGAG_DESP.CODDESPESA%TYPE,
    p_sequsuario     IN MEGAG_DESP_APROVADORES.SEQUSUARIO%TYPE,
    p_status         IN MEGAG_DESP_APROVACAO.STATUS%TYPE,
    p_pago           IN MEGAG_DESP.PAGO%TYPE,
    p_observacao     IN MEGAG_DESP.OBSERVACAO%TYPE,
    p_msg_retorno    OUT VARCHAR2
);

PROCEDURE PRC_INS_MEGAG_DESP_ARQUIVO (
    p_CODDESPESA       IN MEGAG_DESP_ARQUIVO.CODDESPESA%TYPE,
    p_NOMEARQUIVO      IN MEGAG_DESP_ARQUIVO.NOMEARQUIVO%TYPE,
    p_TIPOARQUIVO      IN MEGAG_DESP_ARQUIVO.TIPOARQUIVO%TYPE DEFAULT NULL,
    p_CODARQUIVO_OUT   OUT MEGAG_DESP_ARQUIVO.CODARQUIVO%TYPE
);

PROCEDURE PRC_SEL_MEGAG_DESP_ARQUIVO (
    p_CODARQUIVO   IN MEGAG_DESP_ARQUIVO.CODARQUIVO%TYPE DEFAULT NULL,
    p_CODDESPESA   IN MEGAG_DESP_ARQUIVO.CODDESPESA%TYPE DEFAULT NULL,
    p_RESULT       OUT SYS_REFCURSOR
);

PROCEDURE PRC_UPD_MEGAG_DESP_ARQUIVO (
    p_CODARQUIVO   IN MEGAG_DESP_ARQUIVO.CODARQUIVO%TYPE,
    p_NOMEARQUIVO  IN MEGAG_DESP_ARQUIVO.NOMEARQUIVO%TYPE,
    p_TIPOARQUIVO  IN MEGAG_DESP_ARQUIVO.TIPOARQUIVO%TYPE DEFAULT NULL
);

PROCEDURE PRC_DEL_MEGAG_DESP_ARQUIVO (
    p_CODARQUIVO IN MEGAG_DESP_ARQUIVO.CODARQUIVO%TYPE
);

PROCEDURE PRC_INS_MEGAG_DESP_POLIT_CENTRO_CUSTO(
    p_codpolitica        IN  MEGAG_DESP_POLIT_CENTRO_CUSTO.CODPOLITICA%TYPE,
    p_codgrupo           IN  MEGAG_DESP_POLIT_CENTRO_CUSTO.CODGRUPO%TYPE,
    p_sequsuario         IN  MEGAG_DESP_POLIT_CENTRO_CUSTO.SEQUSUARIO%TYPE,
    p_centrocusto        IN  MEGAG_DESP_POLIT_CENTRO_CUSTO.CENTROCUSTO%TYPE,
    p_nivel_aprovacao    IN  MEGAG_DESP_POLIT_CENTRO_CUSTO.NIVEL_APROVACAO%TYPE,
    p_descricao          IN  MEGAG_DESP_POLIT_CENTRO_CUSTO.DESCRICAO%TYPE DEFAULT NULL,
    p_codpolit_cc        OUT MEGAG_DESP_POLIT_CENTRO_CUSTO.CODPOLIT_CC%TYPE,
    p_msg_retorno        OUT VARCHAR2
);

PROCEDURE PRC_LIST_MEGAG_DESP_POLIT_CENTRO_CUSTO(
    p_codpolitica IN  MEGAG_DESP_POLIT_CENTRO_CUSTO.CODPOLITICA%TYPE DEFAULT NULL,
    p_cursor      OUT SYS_REFCURSOR
);

PROCEDURE PRC_UPD_MEGAG_DESP_POLIT_CENTRO_CUSTO(
    p_codpolit_cc        IN  MEGAG_DESP_POLIT_CENTRO_CUSTO.CODPOLIT_CC%TYPE,
    p_codgrupo           IN  MEGAG_DESP_POLIT_CENTRO_CUSTO.CODGRUPO%TYPE,
    p_sequsuario         IN  MEGAG_DESP_POLIT_CENTRO_CUSTO.SEQUSUARIO%TYPE,
    p_centrocusto        IN  MEGAG_DESP_POLIT_CENTRO_CUSTO.CENTROCUSTO%TYPE,
    p_nivel_aprovacao    IN  MEGAG_DESP_POLIT_CENTRO_CUSTO.NIVEL_APROVACAO%TYPE,
    p_descricao          IN  MEGAG_DESP_POLIT_CENTRO_CUSTO.DESCRICAO%TYPE DEFAULT NULL,
    p_msg_retorno        OUT VARCHAR2
);

PROCEDURE PRC_DEL_MEGAG_DESP_POLIT_CENTRO_CUSTO(
    p_codpolit_cc IN  MEGAG_DESP_POLIT_CENTRO_CUSTO.CODPOLIT_CC%TYPE,
    p_msg_retorno OUT VARCHAR2
);

PROCEDURE PRC_INS_MEGAG_DESP_GRUPO(
    p_nomegrupo     IN MEGAG_DESP_GRUPO.NOMEGRUPO%TYPE,
    p_msg_retorno   OUT VARCHAR2
);

PROCEDURE PRC_LIST_MEGAG_DESP_GRUPO(
    p_cursor OUT SYS_REFCURSOR
);

PROCEDURE PRC_UPD_MEGAG_DESP_GRUPO(
    p_codgrupo      IN MEGAG_DESP_GRUPO.CODGRUPO%TYPE,
    p_nomegrupo     IN MEGAG_DESP_GRUPO.NOMEGRUPO%TYPE,
    p_msg_retorno   OUT VARCHAR2
);

PROCEDURE PRC_DEL_MEGAG_DESP_GRUPO(
    p_codgrupo      IN MEGAG_DESP_GRUPO.CODGRUPO%TYPE,
    p_msg_retorno   OUT VARCHAR2
);

-- INSERT
PROCEDURE PRC_INS_MEGAG_DESP_RATEIO(
    p_coddespesa         IN MEGAG_DESP_RATEIO.CODDESPESA%TYPE,
    p_seqcentroresultado IN MEGAG_DESP_RATEIO.SEQCENTRORESULTADO%TYPE,
    p_centrocusto        IN MEGAG_DESP_RATEIO.CENTROCUSTO%TYPE,
    p_valorrateio        IN MEGAG_DESP_RATEIO.VALORRATEIO%TYPE,
    p_codrateio          OUT NUMBER
);

-- LIST
PROCEDURE PRC_LIST_MEGAG_DESP_RATEIO(
    p_coddespesa IN MEGAG_DESP_RATEIO.CODDESPESA%TYPE,
    p_cursor     OUT SYS_REFCURSOR
);

-- UPDATE
PROCEDURE PRC_UPD_MEGAG_DESP_RATEIO(
    p_codrateio   IN MEGAG_DESP_RATEIO.CODRATEIO%TYPE,
    p_valorrateio IN MEGAG_DESP_RATEIO.VALORRATEIO%TYPE
);

-- DELETE
PROCEDURE PRC_DEL_MEGAG_DESP_RATEIO(
    p_codrateio IN MEGAG_DESP_RATEIO.CODRATEIO%TYPE
);

PROCEDURE PRC_INS_MEGAG_DESP_FORNEC_AUX(
	p_codfornecaux		 IN MEGAG_DESP_FORNEC_AUX.CODFORNECAUX%TYPE,
    p_nomerazao          IN MEGAG_DESP_FORNEC_AUX.NOMERAZAO%TYPE,
    p_fantasia           IN MEGAG_DESP_FORNEC_AUX.FANTASIA%TYPE,
    p_logradouro         IN MEGAG_DESP_FORNEC_AUX.LOGRADOURO%TYPE,
    p_bairro             IN MEGAG_DESP_FORNEC_AUX.BAIRRO%TYPE,
    p_cidade             IN MEGAG_DESP_FORNEC_AUX.CIDADE%TYPE,
    p_uf                 IN MEGAG_DESP_FORNEC_AUX.UF%TYPE,
    p_cep                IN MEGAG_DESP_FORNEC_AUX.CEP%TYPE,
    p_fisicajuridica     IN MEGAG_DESP_FORNEC_AUX.FISICAJURIDICA%TYPE,
    p_nrocgccpf          IN MEGAG_DESP_FORNEC_AUX.NROCGCCPF%TYPE,
    p_digcgccpf          IN MEGAG_DESP_FORNEC_AUX.DIGCGCCPF%TYPE,
    p_foneddd1           IN MEGAG_DESP_FORNEC_AUX.FONEDDD1%TYPE,
    p_fonenro1           IN MEGAG_DESP_FORNEC_AUX.FONENRO1%TYPE,
    p_datahoraalteracao  IN MEGAG_DESP_FORNEC_AUX.DATAHORAALTERACAO%TYPE,
    p_msg_retorno        OUT VARCHAR2
);

PROCEDURE PRC_LIST_MEGAG_DESP_FORNEC_AUX(
    p_cursor OUT SYS_REFCURSOR
);

PROCEDURE PRC_UPD_MEGAG_DESP_FORNEC_AUX (
	p_codfornecaux		 IN MEGAG_DESP_FORNEC_AUX.CODFORNECAUX%TYPE,
    p_nomerazao          IN MEGAG_DESP_FORNEC_AUX.NOMERAZAO%TYPE,
    p_fantasia           IN MEGAG_DESP_FORNEC_AUX.FANTASIA%TYPE,
    p_logradouro         IN MEGAG_DESP_FORNEC_AUX.LOGRADOURO%TYPE,
    p_bairro             IN MEGAG_DESP_FORNEC_AUX.BAIRRO%TYPE,
    p_cidade             IN MEGAG_DESP_FORNEC_AUX.CIDADE%TYPE,
    p_uf                 IN MEGAG_DESP_FORNEC_AUX.UF%TYPE,
    p_cep                IN MEGAG_DESP_FORNEC_AUX.CEP%TYPE,
    p_fisicajuridica     IN MEGAG_DESP_FORNEC_AUX.FISICAJURIDICA%TYPE,
    p_nrocgccpf          IN MEGAG_DESP_FORNEC_AUX.NROCGCCPF%TYPE,
    p_digcgccpf          IN MEGAG_DESP_FORNEC_AUX.DIGCGCCPF%TYPE,
    p_foneddd1           IN MEGAG_DESP_FORNEC_AUX.FONEDDD1%TYPE,
    p_fonenro1           IN MEGAG_DESP_FORNEC_AUX.FONENRO1%TYPE,
    p_msg_retorno        OUT VARCHAR2
);

PROCEDURE PRC_DEL_MEGAG_DESP_FORNEC_AUX (
    p_codfornecaux IN MEGAG_DESP_FORNEC_AUX.CODFORNECAUX%TYPE,
    p_msg_retorno  OUT VARCHAR2
);

PROCEDURE PRC_INS_MEGAG_DESP_FORNECEDOR(
    p_SEQPESSOA       IN  GE_PESSOA.SEQPESSOA%TYPE,
    p_CODDESPESA     IN  MEGAG_DESP.CODDESPESA%TYPE,
    p_NROCGCCPF      IN  GE_PESSOA.NROCGCCPF%TYPE,
    p_DIGCGCCPF      IN  GE_PESSOA.DIGCGCCPF%TYPE,
    p_NOMERAZAO      IN  GE_PESSOA.NOMERAZAO%TYPE
);

PROCEDURE PRC_LIST_MEGAG_DESP_FORNECEDOR(
    p_cursor OUT SYS_REFCURSOR
);

END PKG_MEGAG_DESP_CADASTRO;
