-- INSERT
CREATE OR REPLACE PROCEDURE PRC_INS_MEGAG_DESP_RATEIO(
    p_coddespesa         IN MEGAG_DESP_RATEIO.CODDESPESA%TYPE,
    p_seqcentroresultado IN MEGAG_DESP_RATEIO.SEQCENTRORESULTADO%TYPE,
    p_centrocusto        IN MEGAG_DESP_RATEIO.CENTROCUSTO%TYPE,
    p_valorrateio        IN MEGAG_DESP_RATEIO.VALORRATEIO%TYPE,
    p_codrateio          OUT NUMBER
) AS
BEGIN
    INSERT INTO MEGAG_DESP_RATEIO (
        CODDESPESA, SEQCENTRORESULTADO, CENTROCUSTO, VALORRATEIO
    ) VALUES (
        p_coddespesa, p_seqcentroresultado, p_centrocusto, p_valorrateio
    )
    RETURNING CODRATEIO INTO p_codrateio;
END PRC_INS_MEGAG_DESP_RATEIO;
/

-- LIST
CREATE OR REPLACE PROCEDURE PRC_LIST_MEGAG_DESP_RATEIO(
    p_coddespesa IN MEGAG_DESP_RATEIO.CODDESPESA%TYPE,
    p_cursor     OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT CODRATEIO, CODDESPESA, SEQCENTRORESULTADO, CENTROCUSTO, VALORRATEIO
    FROM MEGAG_DESP_RATEIO
    WHERE CODDESPESA = p_coddespesa
    ORDER BY CENTROCUSTO;
END PRC_LIST_MEGAG_DESP_RATEIO;
/

-- UPDATE
CREATE OR REPLACE PROCEDURE PRC_UPD_MEGAG_DESP_RATEIO(
    p_codrateio   IN MEGAG_DESP_RATEIO.CODRATEIO%TYPE,
    p_valorrateio IN MEGAG_DESP_RATEIO.VALORRATEIO%TYPE
) AS
BEGIN
    UPDATE MEGAG_DESP_RATEIO
    SET VALORRATEIO = p_valorrateio
    WHERE CODRATEIO = p_codrateio;
END PRC_UPD_MEGAG_DESP_RATEIO;
/

-- DELETE
CREATE OR REPLACE PROCEDURE PRC_DEL_MEGAG_DESP_RATEIO(
    p_codrateio IN MEGAG_DESP_RATEIO.CODRATEIO%TYPE
) AS
BEGIN
    DELETE FROM MEGAG_DESP_RATEIO
    WHERE CODRATEIO = p_codrateio;
END PRC_DEL_MEGAG_DESP_RATEIO;
/
