--INSERT
CREATE OR REPLACE PROCEDURE PRC_INS_MEGAG_DESP_TIPO(
    p_DESCRICAO IN MEGAG_DESP_TIPO.DESCRICAO%TYPE
)
IS
BEGIN
    INSERT INTO MEGAG_DESP_TIPO(
        DESCRICAO
)
    VALUES(
        p_DESCRICAO
);
    
END PRC_INS_MEGAG_DESP_TIPO;
/

--SELECT 
CREATE OR REPLACE PROCEDURE PRC_LIST_MEGAG_DESP_TIPO(
    p_CODTIPODESPESA IN  MEGAG_DESP_TIPO.CODTIPODESPESA%TYPE,
    p_DESCRICAO      IN  MEGAG_DESP_TIPO.DESCRICAO%TYPE, 
    p_RESULT         OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN p_RESULT FOR
        SELECT * FROM MEGAG_DESP_TIPO
        --caso não coloque a despesa trazer tudo:
         WHERE (p_CODTIPODESPESA IS NULL OR CODTIPODESPESA = p_CODTIPODESPESA)
           AND (p_DESCRICAO IS NULL OR DESCRICAO LIKE '%' || p_DESCRICAO || '%');
END PRC_LIST_MEGAG_DESP_TIPO;
/

--UPDATE

CREATE OR REPLACE PROCEDURE PRC_UPD_MEGAG_DESP_TIPO(
    p_CODTIPODESPESA IN MEGAG_DESP_TIPO.CODTIPODESPESA%TYPE,
    p_DESCRICAO      IN MEGAG_DESP_TIPO.DESCRICAO%TYPE
)
IS
BEGIN
/*
* REGRA DE NEGÓCIO
*/
    UPDATE MEGAG_DESP_TIPO
       SET DESCRICAO  = p_DESCRICAO,
           DTAALTERACAO = SYSDATE
     WHERE CODTIPODESPESA = p_CODTIPODESPESA;

END PRC_UPD_MEGAG_DESP_TIPO;
/

--DELETE

CREATE OR REPLACE PROCEDURE PRC_DEL_MEGAG_DESP_TIPO(
    p_CODTIPODESPESA IN MEGAG_DESP_TIPO.CODTIPODESPESA%TYPE
)
IS
BEGIN
/*
* REGRA DE NEGÓCIO
*/
    DELETE FROM MEGAG_DESP_TIPO
     WHERE CODTIPODESPESA = p_CODTIPODESPESA;

END PRC_DEL_MEGAG_DESP_TIPO;
/

